PROJECT_PRN211/Cake/Models/Order.cs
using Cake.Models;
using System;
using System.Collections.Generic;

namespace Cake.Models
{
    public partial class Order
    {
        public Order()
        {
            OrderItems = new HashSet<OrderItem>();
        }

        public int OrderId { get; set; }
        public int? CustomerId { get; set; }
        public DateTime OrderDate { get; set; }
        public string Status { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string? Note { get; set; }

        public virtual User? Customer { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}

PROJECT_PRN211/Cake/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cake.Models;
using Cake.Models.Authentication;

namespace Cake.Controllers
{
    public class OrdersController : Controller
    {
        private readonly BakeryCakeContext _context;

        public OrdersController(BakeryCakeContext context)
        {
            _context = context;
        }
        public string getRole()
        {
            User u = _context.Users.Where(x => x.UserName.Equals(HttpContext.Session.GetString("UserName"))).SingleOrDefault();
            return u.RoleName;
        }

        [Authentication]
        // GET: Orders
        public async Task<IActionResult> Index()
        {
            if (getRole().Equals("Admin") || getRole().Equals("Staff"))
            {
                var bakeryCakeContext = _context.Orders.Include(o => o.Customer).OrderByDescending(x=> x.OrderId);
                return View(await bakeryCakeContext.ToListAsync());
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        [Authentication]
        public async Task<IActionResult> list()
		{
            var userName = HttpContext.Session.GetString("UserName");
            List<Order> orders = _context.Orders
                                         .Include(o => o.Customer)
                                         .Where(o => o.Customer.UserName == userName)
                                         .OrderByDescending(x => x.OrderId)
										 .ToList();
            ViewData["order"] = orders.ToList();
			return View();
		}
        [Authentication]
        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Customer)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            ViewData["orderItems"]= _context.OrderItems.Include(x=>x.Product).Where(x => x.OrderId==order.OrderId).ToList();
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }
        [Authentication]
        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["CustomerId"] = new SelectList(_context.Users, "UserId", "UserId");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authentication]
        public async Task<IActionResult> Create([Bind("OrderId,CustomerId,OrderDate,IsApprove")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Users, "UserId", "UserId", order.CustomerId);
            return View(order);
        }
        [Authentication]
        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Users, "UserId", "UserId", order.CustomerId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authentication]
        public async Task<IActionResult> Edit(int id, String status)
        {
            if (getRole().Equals("Admin") || getRole().Equals("Staff"))
            {
                Order o = _context.Orders.FirstOrDefault(x => x.OrderId == id);
                o.Status = status;
                _context.Update(o);
                _context.SaveChanges();

                var bakeryCakeContext = _context.Orders.Include(o => o.Customer);
                return View("Index", await bakeryCakeContext.ToListAsync());
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: Orders/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null || _context.Orders == null)
        //    {
        //        return NotFound();
        //    }

        //    var order = await _context.Orders
        //        .Include(o => o.Customer)
        //        .FirstOrDefaultAsync(m => m.OrderId == id);
        //    if (order == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(order);
        //}

        // POST: Orders/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        [Authentication]
        public async Task<IActionResult> Delete(int id)
        {
            if (_context.Orders == null)
            {
                return Problem("Entity set 'BakeryCakeContext.Orders'  is null.");
            }
            var order = await _context.Orders.FindAsync(id);
            List<OrderItem> items = _context.OrderItems.Where(x => x.OrderId == order.OrderId).ToList();
            if (order != null)
            {
                foreach (var item in items)
                {
                    _context.OrderItems.Remove(item);
                }
                
                _context.Orders.Remove(order);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(list));
        }

        private bool OrderExists(int id)
        {
          return (_context.Orders?.Any(e => e.OrderId == id)).GetValueOrDefault();
        }
    }
}

PROJECT_PRN211/Cake/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cake.Models.Authentication;
using Cake.Models;

namespace Cake.Controllers
{
    public class UsersController : Controller
    {
        private readonly BakeryCakeContext _context;

        public UsersController(BakeryCakeContext context)
        {
            _context = context;
        }
        public string getRole()
        {
            User u = _context.Users.Where(x=> x.UserName.Equals(HttpContext.Session.GetString("UserName"))).SingleOrDefault();
            return u.RoleName;
        }
        [Authentication]
        //[Authentication]
        // GET: Users
        public async Task<IActionResult> Index()
        {
            if (getRole().Equals("Admin"))
            {
                return _context.Users != null ?
                          View(await _context.Users.ToListAsync()) :
                          Problem("Entity set 'BakeryCakeContext.Users'  is null.");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        [Authentication]
        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id, string? mod)
        {
            if (mod != null)
            {
                ViewData["view"] = "view";
            }
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }
        [Authentication]
        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authentication]
        public async Task<IActionResult> Create([Bind("UserId,UserName,Password,Name,Phone,Mail,Sex,Dob,Avatar,IsActive")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }
        [Authentication]
        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authentication]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,UserName,Password,Name,Phone,Mail,Sex,Dob,Avatar,IsActive")] User user)
        {
            if (id != user.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }
        [Authentication]
        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (_context.Users == null)
            {
                return Problem("Entity set 'BakeryCakeContext.Users'  is null.");
            }
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
          return (_context.Users?.Any(e => e.UserId == id)).GetValueOrDefault();
        }
    }
}

PROJECT_PRN211/Cake/Views/Orders/Create.cshtml
@model Cake.Models.Order

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" class ="form-control" asp-items="ViewBag.CustomerId"></select>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

PROJECT_PRN211/Cake/Views/Orders/Delete.cshtml
@model Cake.Models.Order

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.UserId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="OrderId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PROJECT_PRN211/Cake/Views/Orders/Details.cshtml
@using Microsoft.EntityFrameworkCore;
@model Cake.Models.Order

@{
    ViewData["Title"] = "Details";
    Layout = "_Layout";
}

<section class="banner_area">
    <div class="container">
        <div class="banner_text">
            <h3>Order Details</h3>
            <ul>
                <li><a href="/Home/Index">Home</a></li>
            </ul>
        </div>
    </div>
</section>
<section class="contact_form_area p_100">
    <div class="container">
        <div class="main_title">
            <h2>Order Details</h2>
        </div>
        <hr style="width:36%;float:left" /><br />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.OrderId)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.OrderId)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Customer)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Customer.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Customer.Phone)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Phone)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Customer.Address)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Address)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.OrderDate)
            </dt>
            <dd class="col-sm-10">
                @Model.OrderDate.ToString("dd/MM/yyyy")
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Note)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Note)
            </dd>
            <dt class="col-sm-2">
                Status
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Status)
            </dd>
            
        </dl>
        <div class="row">
            <table class="table" style="width: 60%">
                <thead>
                    <tr>
                        <th>
                            Product Name
                        </th>
                        <th>
                            Quantity
                        </th>
                        <th>
                            UnitPrice
                        </th>
                        <th>
                            Price
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.orderItems)
                    {
                        <tr>
                            <td>
                                @item.Product.Name
                            </td>
                            <td>
                                @item.Quantity
                            </td>
                            <td>
                                @string.Format("{0:0.00}", item.Product.UnitPrice)$
                            </td>
                            <td>
                                @string.Format("{0:0.00}", item.Quantity * item.Product.UnitPrice)$
                            </td>
                        </tr>
                    }
                    <tr>
                        <td></td>
                        <td></td>
                        <th>Ship Cost</th>
                        <td>
                            5.00$
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <th>Total</th>
                        <td>
                            @{
                                BakeryCakeContext _context = new();
                                List<OrderItem> oi = _context.OrderItems.Include(x => x.Product).Where(x => x.OrderId == Model.OrderId).ToList();
                                decimal price = 0;
                                foreach (var i in oi)
                                {
                                    price += i.Product.UnitPrice * i.Quantity;
                                }
                                price += 5;
                                @string.Format("{0:0.00}",price)

                                <span>$</span>
                            }
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</section>

PROJECT_PRN211/Cake/Views/Orders/Edit.cshtml
@model Cake.Models.Order

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrderId" />
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" class="form-control" asp-items="ViewBag.CustomerId"></select>
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

PROJECT_PRN211/Cake/Views/Orders/Index.cshtml
@using Microsoft.EntityFrameworkCore;
@model IEnumerable<Cake.Models.Order>

@{
    Layout = "_Layout";
    ViewData["Title"] = "Index";
}

<section class="banner_area">
    <div class="container">
        <div class="banner_text">
            <h3>Orders List</h3>
            <ul>
                <li><a href="/Home/Index">Home</a></li>
            </ul>
        </div>
    </div>
</section>
<section class="contact_form_area p_100">
    <div class="container">
        <div class="main_title">
            <h2>Orders List</h2>
        </div>
        <div class="row">
            <table class="table" style="width: 80%">
                <thead>
                    <tr>
                        <th>Order Id</th>
                        <th>
                            @Html.DisplayNameFor(model => model.Customer)
                        </th>
                        <th>
                            Order Date
                        </th>
                        <th>Price</th>
                        <th>
                            Status
                        </th>
                        
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.OrderId</td>
                            <td>
                                <a asp-controller="Users" asp-action="Details" asp-route-id="@item.CustomerId" asp-route-mod="view">@item.Customer.Name</a>
                            </td>
                            <td>
                                @item.OrderDate.ToString("dd/MM/yyyy")
                            </td>
                            <td>
                                @{
                                    BakeryCakeContext _context = new() ;
                                    List<OrderItem> oi = _context.OrderItems.Include(x => x.Product).Where(x => x.OrderId == item.OrderId).ToList();
                                    decimal price = 0;
                                    foreach (var i in oi)
                                    {
                                        price += i.Product.UnitPrice * i.Quantity;
                                    }
                                    price += 5;
                                    @string.Format("{0:0.00}",price)

                                    <span>$</span>
                                }
                            </td>
                            <td>
                                  <span class="product_task_inner">
                                    <form id="@item.OrderId.ToString()" method="post" asp-action="Edit" asp-controller="Orders">
                                        <input name="id" value="@item.OrderId" type="text" hidden/>
                                        @{
                                            if (item.Status.Equals("Processing"))
                                            {
                                                <select name="status" class="short" onchange="changeStatus(@item.OrderId.ToString())">
                                                    <option value="Processing" data-display="Processing">Processing</option>
                                                    <option value="Confirmed">Confirmed</option>
                                                    <option value="Reject">Reject</option>
                                                    <option value="Done">Done</option>
                                                </select>
                                            }
                                            if (item.Status.Equals("Confirmed"))
                                            {
                                                <select name="status" class="short" onchange="changeStatus(@item.OrderId)">
                                                    <option value="Confirmed" data-display="Confirmed">Confirmed</option>
                                                    <option value="Done">Done</option>
                                                </select>
                                            }
                                            if (item.Status.Equals("Reject"))
                                            {
                                                <select class="short" disabled>
                                                    <option value="Reject" data-display="Reject">Reject</option>
                                                </select>
                                            }
                                            if (item.Status.Equals("Done"))
                                            {
                                                <select class="short" disabled>
                                                    <option value="Done" data-display="Done">Done</option>
                                                </select>
                                            }
                                        }
                                      </form>
                                  </span>
                                
                            </td>
                            <td>
                                @*<a asp-action="Edit" asp-route-id="@item.OrderId">Edit</a> |*@
                                <a asp-action="Details" asp-route-id="@item.OrderId"><i class="fa fa-pencil"></i></a>
                                @*<a asp-action="Delete" asp-route-id="@item.OrderId">Delete</a>*@
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</section>

<script>
    function changeStatus(id){
        document.getElementById(id).submit();
    }
</script>

PROJECT_PRN211/Cake/Views/Orders/List.cshtml
@using Microsoft.EntityFrameworkCore;

@{
    Layout = "_Layout";
    ViewData["Title"] = "Index";
}

<section class="banner_area">
    <div class="container">
        <div class="banner_text">
            <h3>Orders List</h3>
            <ul>
                <li><a href="/Home/Index">Home</a></li>
            </ul>
        </div>
    </div>
</section>
<section class="contact_form_area p_100">
    <div class="container">
        <div class="main_title">
            <h2>Orders List</h2>
        </div>
        <div class="row">
            <table class="table" style="width: 80%">
                <thead>
                    <tr>
                        <th>Order Id</th>
                        <th>
                            Customer
                        </th>
                        <th>
                            Order Date
                        </th>
                        <th>Price</th>
                        <th>
                            Status
                        </th>

                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Order item in ViewBag.order)
                    {
                        <tr>
                            <td>@item.OrderId</td>
                            <td>
                                <a asp-controller="Users" asp-action="Details" asp-route-id="@item.CustomerId" asp-route-mod="view">@item.Customer.Name</a>
                            </td>
                            <td>
                                @item.OrderDate.ToString("dd/MM/yyyy")
                            </td>
                            <td>
                                @{
                                    BakeryCakeContext _context = new();
                                    List<OrderItem> oi = _context.OrderItems.Include(x => x.Product).Where(x => x.OrderId == item.OrderId).ToList();
                                    decimal price = 0;
                                    foreach (var i in oi)
                                    {
                                        price += i.Product.UnitPrice * i.Quantity;
                                    }
                                    price += 5;
                                    @string.Format("{0:0.00}",price)

                                    <span>$</span>
                                }
                            </td>
                            <td>
                                @item.Status
                            </td>
                            <td>
                                @*<a asp-action="Edit" asp-route-id="@item.OrderId">Edit</a> |*@
                                <a asp-action="Details" asp-route-id="@item.OrderId"><i class="fa fa-pencil"></i></a>
                                @{
                                    
                                    Order o = _context.Orders.FirstOrDefault(x => x.OrderId == item.OrderId);
                                    if (o.Status.Equals("Processing"))
                                    {
                                        <span> | </span>
                                        <a asp-action="Delete" asp-route-id="@item.OrderId"><i class="fa fa-times"></i></a>
                                    }
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</section>