PROJECT_PRN211/Cake/Models/Blog.cs
using System;
using System.Collections.Generic;

namespace Cake.Models
{
    public partial class Blog
    {
        public Blog()
        {
            Comments = new HashSet<Comment>();
        }

        public int BlogId { get; set; }
        public string? BlogTitle { get; set; }
        public string? Description { get; set; }
        public int? CreateBy { get; set; }
		public string? image { get; set; }
		public DateTime CreateDate { get; set; }

        public virtual User? CreateByNavigation { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}

PROJECT_PRN211/Cake/Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cake.Models.Authentication;
using Cake.Models;

namespace Cake.Controllers
{
    public class BlogsController : Controller
    {
        private readonly BakeryCakeContext _context;

        public BlogsController(BakeryCakeContext context)
        {
            _context = context;
        }
        public string getRole()
        {
            User u = _context.Users.Where(x => x.UserName.Equals(HttpContext.Session.GetString("UserName"))).SingleOrDefault();
            return u.RoleName;
        }
        [Authentication]
        // GET: Blogs
        public async Task<IActionResult> Index()
        {
            //var bakeryCakeContext = _context.Blogs.Include(b => b.CreateByNavigation);
            //List<Blog> BlogsList = await _context.Blogs.ToListAsync();
            List<Blog> BlogsList = _context.Blogs.Include(b => b.CreateByNavigation).ToList();

            var totalComment = _context.Comments
                .GroupBy(b => b.BlogId)
                .Select(g => new { BlogID = g.Key, Count = g.Count() })
                .ToList();

            ViewBag.TotalComment = totalComment;
            ViewBag.BlogsList = BlogsList;

            return View();
        }
        [Authentication]
        // GET: Blogs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Blogs == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .Include(b => b.CreateByNavigation)
                .FirstOrDefaultAsync(m => m.BlogId == id);
            if (blog == null)
            {
                return NotFound();
            }

            var comments = await _context.Comments
                .Include(x=>x.OwnerNavigation)
                .Where(c => c.BlogId == id && c.ParentId == null).ToListAsync();

            var listBlog = _context.Blogs
				.Include(b => b.CreateByNavigation)
				.Where(x=>x.BlogId!=id)
                .OrderByDescending(x=>x.CreateDate)
                .Take(4).ToList();

            ViewData["listBlog"] = listBlog;
			ViewData["count"] = _context.Comments
				.Include(x => x.OwnerNavigation)
				.Where(c => c.BlogId == id).ToList().Count;
            ViewData["cmt"] = comments;
            ViewData["blog"] = blog;

			return View();
        }
        [Authentication]
        // GET: Blogs/Create
        public IActionResult Create()
        {
            if (getRole().Equals("Admin") || getRole().Equals("Staff"))
            {
                ViewData["CreateBy"] = new SelectList(_context.Users, "UserId", "UserId");
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
                
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authentication]
        public async Task<IActionResult> Create([Bind("BlogId,BlogTitle,Description,Image")] Blog blog)
        {
            if (getRole().Equals("Admin") || getRole().Equals("Staff"))
            {
                if (ModelState.IsValid)
                {
                    blog.CreateDate = DateTime.Now;
                    blog.CreateBy = _context.Users.Where(x => x.UserName.Equals(HttpContext.Session.GetString("UserName"))).SingleOrDefault().UserId;
                    _context.Add(blog);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                ViewData["CreateBy"] = new SelectList(_context.Users, "UserId", "UserId", blog.CreateBy);
                return View(blog);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
           
        }
        [Authentication]
        // GET: Blogs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (getRole().Equals("Admin") || getRole().Equals("Staff"))
            {
                if (id == null || _context.Blogs == null)
                {
                    return NotFound();
                }

                var blog = await _context.Blogs.FindAsync(id);
                if (blog == null)
                {
                    return NotFound();
                }
                ViewData["CreateBy"] = new SelectList(_context.Users, "UserId", "UserId", blog.CreateBy);
                return View(blog);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authentication]
        public async Task<IActionResult> Edit(int id, [Bind("BlogId,BlogTitle,Description,CreateBy,CreateDate")] Blog blog)
        {
            if (getRole().Equals("Admin") || getRole().Equals("Staff"))
            {
                if (id != blog.BlogId)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(blog);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!BlogExists(blog.BlogId))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                ViewData["CreateBy"] = new SelectList(_context.Users, "UserId", "UserId", blog.CreateBy);
                return View(blog);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            
        }
        [Authentication]
        // GET: Blogs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (getRole().Equals("Admin") || getRole().Equals("Staff"))
            {
                if (id == null || _context.Blogs == null)
                {
                    return NotFound();
                }

                var blog = await _context.Blogs
                    .Include(b => b.CreateByNavigation)
                    .FirstOrDefaultAsync(m => m.BlogId == id);
                if (blog == null)
                {
                    return NotFound();
                }

                return View(blog);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            
        }

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authentication]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (getRole().Equals("Admin") || getRole().Equals("Staff"))
            {
                if (_context.Blogs == null)
                {
                    return Problem("Entity set 'BakeryCakeContext.Blogs'  is null.");
                }
                var blog = await _context.Blogs.FindAsync(id);
                if (blog != null)
                {
                    _context.Blogs.Remove(blog);
                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            
        }

        private bool BlogExists(int id)
        {
            return (_context.Blogs?.Any(e => e.BlogId == id)).GetValueOrDefault();
        }
        [Authentication]
        public async Task<IActionResult> List()
        {
            if (getRole().Equals("Admin") || getRole().Equals("Staff"))
            {
                //var bakeryCakeContext = _context.Blogs.Include(b => b.CreateByNavigation);
                //List<Blog> BlogsList = await _context.Blogs.ToListAsync();
                List<Blog> BlogsList = _context.Blogs.Include(b => b.CreateByNavigation).ToList();

                var totalComment = _context.Comments
                    .GroupBy(b => b.BlogId)
                    .Select(g => new { BlogID = g.Key, Count = g.Count() })
                    .ToList();

                ViewBag.TotalComment = totalComment;
                ViewBag.BlogsList = BlogsList;

                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            
        }
    }
}

PROJECT_PRN211/Cake/Controllers/CommentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cake.Models.Authentication;
using Cake.Models;

namespace Cake.Controllers
{
    public class CommentController : Controller
    {
        private readonly BakeryCakeContext _context;
        public CommentController(BakeryCakeContext context)
        {
            _context = context;
        }
        [HttpPost]
        public IActionResult Add(int BlogID, int? parentID, string message)
        {
            User u = _context.Users.Where(x => x.UserName.Equals(HttpContext.Session.GetString("UserName"))).SingleOrDefault();
            Comment c = new()
            {
                BlogId = BlogID,
                ParentId = parentID,
                Description = message,
                CreateDate = DateTime.Now,
                Owner = u.UserId
            };
			_context.Comments.Add(c);
            _context.SaveChanges();

			
			return RedirectToAction("Details", "Blogs", new {id = BlogID});
        }
    }
}

PROJECT_PRN211/Cake/Views/Blogs/Create.cshtml
@model Blog

@{
    ViewData["Title"] = "Create";
    Layout = "_Layout";
    User u = @ViewBag.owner;
}

<section class="banner_area">
    <div class="container">
        <div class="banner_text">
            <h3>Create Product</h3>
            <ul>
                <li><a href="index.html">Home</a></li>
                <li><a href="single-blog.html">Create Product</a></li>
            </ul>
        </div>
    </div>
</section>
<!--================End Main Header Area =================-->
<!--================Contact Form Area =================-->
<section class="contact_form_area p_100">
    <div class="container">
        <div class="main_title">
            <h2>Create Product</h2>
            <h5>Added a new cake bakery model of the shop</h5>
        </div>
        <div class="row">
            <div class="col-lg-7">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="BlogTitle" class="control-label"></label>
                        <input asp-for="BlogTitle" class="form-control" />
                        <span asp-validation-for="BlogTitle" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="image" class="control-label"></label>
                        <input asp-for="image" class="form-control" />
                        <span asp-validation-for="image" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
            <div class="col-lg-4 offset-md-1">
                <div class="contact_details">
                    <div class="contact_d_item">
                        <h3>Address :</h3>
                        <p>54B, Tailstoi Town 5238 <br /> La city, IA 522364</p>
                    </div>
                    <div class="contact_d_item">
                        <h5>Phone : <a href="tel:01372466790">01372.466.790</a></h5>
                        <h5>Email : <a href="mailto:rockybd1995@gmail.com">rockybd1995@gmail.com</a></h5>
                    </div>
                    <div class="contact_d_item">
                        <h3>Opening Hours :</h3>
                        <p>8:00 AM – 10:00 PM</p>
                        <p>Monday – Sunday</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@*<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BlogTitle" class="control-label"></label>
                <input asp-for="BlogTitle" class="form-control" />
                <span asp-validation-for="BlogTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreateBy" class="control-label"></label>
                <select asp-for="CreateBy" class ="form-control" asp-items="ViewBag.CreateBy"></select>
            </div>
            <div class="form-group">
                <label asp-for="CreateDate" class="control-label"></label>
                <input asp-for="CreateDate" class="form-control" />
                <span asp-validation-for="CreateDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>*@

PROJECT_PRN211/Cake/Views/Blogs/Delete.cshtml
@model Blog

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Blog</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BlogTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BlogTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateByNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateByNavigation.UserId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BlogId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PROJECT_PRN211/Cake/Views/Blogs/Details.cshtml
@using Microsoft.EntityFrameworkCore;
@model IEnumerable<Cake.Models.Comment>

@{
	Layout = "_Layout";
	ViewBag.Title = "Blogs-Cake Bakery";
	Blog b = ViewBag.blog;
	BakeryCakeContext _context = new();
}
<style>
	
</style>
<!--================End Main Header Area =================-->
<section class="banner_area">
	<div class="container">
		<div class="banner_text">
			<h3>Blog Details</h3>
			<ul>
				<li><a href="index.html">Home</a></li>
				<li><a href="single-blog.html">Blog Details</a></li>
			</ul>
		</div>
	</div>
</section>
<!--================End Main Header Area =================-->
<!--================Blog Main Area =================-->
<section class="main_blog_area p_100">
	<div class="container">
		<div class="row blog_area_inner">
			<div class="col-lg-9">
				<div class="main_blog_inner single_blog_inner">
					<div class="blog_item">
						<div class="blog_img">
							<img class="img-fluid" src="@b.image" alt="">
						</div>
						<div class="blog_text">
							<div class="blog_time">
								<div class="float-left">
									<a>@b.CreateDate.ToString("dd MMM. yyyy")</a>
								</div>
								<div class="float-right">
									<ul class="list_style">
										<li><a>By :  @b.CreateByNavigation.Name</a></li>
										<li><a>Comments: @ViewBag.count</a></li>
									</ul>
								</div>
							</div>
							<a><h4>@b.BlogTitle</h4></a>
							<p>@b.Description</p>
						</div>
					</div>
					<div class="s_comment_list">
						<h3 class="cm_title_br">Comments @ViewBag.count</h3>
						<div class="s_comment_list_inner">
							@{
								foreach (Comment item in ViewBag.cmt)
								{
									<div class="media">
										<div class="d-flex">
											<img src="@item.OwnerNavigation.Avatar" alt="" style="width:60px; height60px; border-radius:50%">
										</div>
										<div class="media-body">
											<a><h4>@item.OwnerNavigation.Name</h4></a>
											<p>@item.Description</p>
											<div class="date_rep">
												<a>@item.CreateDate.ToString("MMM dd yyyy")</a>
												<a class="reply-btn" onclick="createForm(@item.CommentId)">Reply</a>
                                            </div>
											<div id="@item.CommentId" class="s_comment_area" style="display:none">
												<form class="row contact_us_form" method="post" id="contactForm" asp-action="Add" asp-controller="Comment">
													<input type="text" name="BlogID" value="@b.BlogId" hidden />
													<input type="text" name="parentID" value="@item.CommentId" hidden />
													<div class="form-group col-md-12">
														<textarea class="form-control" name="message" id="message" rows="1" placeholder="Wrtie message"></textarea>
													</div>
													<div class="form-group col-md-12">
														<button type="submit" value="submit" class="btn order_s_btn form-control">Submit</button>
													</div>
												</form>
											</div>
											@{
												Comment reply = _context.Comments.Include(x=>x.OwnerNavigation).FirstOrDefault(x=> x.ParentId == item.CommentId);
												if(reply != null)
												{
													<div class="media">
														<div class="d-flex">
															<img src="@reply.OwnerNavigation.Avatar" alt="" style="width:60px; height60px; border-radius:50%">
														</div>
														<div class="media-body">
															<a href="#"><h4>@reply.OwnerNavigation.Name</h4></a>
															<p>@reply.Description</p>
															<div class="date_rep">
																<a>@reply.CreateDate.ToString("MMM dd yyyy")</a>
																<a></a>
															</div>
														</div>
													</div>
												}
											}
										</div>
									</div>
								}
							}
						</div>
					</div>
					<div class="s_comment_area">
						<h3 class="cm_title_br">Leave a Comment</h3>
						<div class="s_comment_inner">
							<form class="row contact_us_form" method="post" id="contactForm" asp-action="Add" asp-controller="Comment">
								<input type="text" name="BlogID" value="@b.BlogId" hidden/>
								<div class="form-group col-md-12">
									<textarea class="form-control" name="message" id="message" rows="1" placeholder="Wrtie message"></textarea>
								</div>
								<div class="form-group col-md-12">
									<button type="submit" value="submit" class="btn order_s_btn form-control">Submit</button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-3">
				<div class="right_sidebar_area">

					<aside class="r_widget categories_widget">
						<div class="r_title">
							<h3>Categories</h3>
						</div>
						<ul class="list_style">
							<li><a>Chocolates</a></li>
							<li><a>Summer Caket</a></li>
							<li><a>Ice Cream</a></li>
							<li><a>Lollipop</a></li>
							<li><a>Sweet</a></li>
							<li><a>Bakery</a></li>
						</ul>
					</aside>
					<aside class="r_widget recent_widget">
						<div class="r_title">
							<h3>Recent News</h3>
						</div>
						<div class="recent_w_inner">
							@{
								foreach (Blog item in ViewBag.listBlog)
								{
									<div class="media">
										<div class="d-flex">
											<img src="@item.image" alt="" style="width:70px; height:62px">
										</div>
										<div class="media-body" >
											<a asp-controller="Blogs" asp-action="Details" asp-route-id="@item.BlogId"><h4>@item.BlogTitle</h4></a>
											<a><p>@item.CreateDate.ToString("dd MMM. yyyy")</p></a>
										</div>
									</div>
								}
							}
						</div>
					</aside>

				</div>
			</div>
		</div>
	</div>
</section>

<script>
	function createForm(parentID) {
		document.getElementById(parentID).style.display = 'block';
	}
</script>

PROJECT_PRN211/Cake/Views/Blogs/Edit.cshtml
@model Blog

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Blog</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BlogId" />
            <div class="form-group">
                <label asp-for="BlogTitle" class="control-label"></label>
                <input asp-for="BlogTitle" class="form-control" />
                <span asp-validation-for="BlogTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreateBy" class="control-label"></label>
                <select asp-for="CreateBy" class="form-control" asp-items="ViewBag.CreateBy"></select>
                <span asp-validation-for="CreateBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreateDate" class="control-label"></label>
                <input asp-for="CreateDate" class="form-control" />
                <span asp-validation-for="CreateDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>

PROJECT_PRN211/Cake/Views/Blogs/Index.cshtml
@{
    Layout = "_Layout";
    ViewBag.Title = "Blogs-Cake Bakery";
    ViewBag.active = 4;

}

<!--================End Main Header Area =================-->
<section class="banner_area">
    <div class="container">
        <div class="banner_text">
            <h3>Blog</h3>
            <ul>
                <li><a href="index.html">Home</a></li>
                <li><a href="blog.html">Blog</a></li>
            </ul>
        </div>
    </div>
</section>
<!--================End Main Header Area =================-->
<!--================Blog Main Area =================-->
<section class="main_blog_area p_100">
    <div class="container">
        <div class="blog_area_inner">
            <div class="main_blog_column row">
                @foreach (var item in ViewBag.BlogsList)
                {

                    <div class="col-lg-6">
                        <div class="blog_item">
                            <div class="blog_img">
                                @*Can thay image*@
                                <img class="img-fluid" src="@item.image" alt="">
                            </div>
                            <div class="blog_text">
                                <div class="blog_time">
                                    <div class="float-left">
                                        <a href="#">@item.CreateDate.ToString("dd MMM. yyyy")</a>
                                    </div>
                                    <div class="float-right">
                                        <ul class="list_style">
                                            <li><a>Create By: @item.CreateByNavigation.Name</a></li>

                                            @*<li><a>Comments: </a></li>*@
                                        </ul>
                                    </div>
                                </div>
                                <a><h4>@item.BlogTitle</h4></a>
                                <p>@item.Description</p>
                                <a class="pink_more" asp-controller="Blogs" asp-action="Details" asp-route-id="@item.BlogId">Read more</a>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <nav aria-label="Page navigation example" class="blog_pagination">
                <ul class="pagination">
                    <li class="page-item active"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                </ul>
            </nav>
        </div>
    </div>
</section>
<!--================End Blog Main Area =================-->

PROJECT_PRN211/Cake/Views/Blogs/List.cshtml
@using Microsoft.EntityFrameworkCore;
@{
    Layout = "_Layout";
    ViewBag.Title = "Blogs-Cake Bakery";
    BakeryCakeContext _context = new();
}
<section class="banner_area">
    <div class="container">
        <div class="banner_text">
            <h3>Blogs List</h3>
            <ul>
                <li><a href="/Home/Index">Home</a></li>
            </ul>
        </div>
    </div>
</section>
<!--================End Blog Main Area =================-->
<section class="contact_form_area p_100">
    <div class="container">
        <div class="main_title">
            <h2>Blogs List</h2>
        </div>
        <div>
            <a asp-action="Create" class="btn" style="background-color: #f195b2; color: #fff; margin-top: -50px">Create</a>
        </div>
        <div class="row">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            BlogID
                        </th>
                        <th>
                            Blog Title
                        </th>
                        <th>
                            Create by
                        </th>
                        <th>
                            CreateDate
                        </th>
                        <th>
                            Number Comments
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Blog item in ViewBag.BlogsList)
                    {
                        <tr>
                            <td>
                                @item.BlogId
                            </td>
                            <td>
                                @item.BlogTitle
                            </td>
                            <td>
                                @item.CreateByNavigation.Name
                            </td>

                            <td>
                                @item.CreateDate.ToString("dd/mm/yyyy");
                            </td>
                            <td>
                                @{
                                    int count = _context.Comments
                                    .Include(x => x.OwnerNavigation)
                                    .Where(c => c.BlogId == item.BlogId).ToList().Count();
                                }
                                @count
                            </td>
                            <td>
                                <a asp-action="Details" asp-route-id="@item.BlogId"><i class="fa fa-file-text"></i></a> |
                                <a asp-action="Edit" asp-route-id="@item.BlogId"><i class="fa fa-pencil"></i></a> |
                                <a asp-action="Delete" asp-route-id="@item.BlogId"><i class="fa fa-times"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</section>